<!DOCTYPE html>
<html>
    <head>
        <title>CV</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link href="cv.css" rel="stylesheet">
    </head>
    <body>
        <section id ="wholepage">
            <section id = "top">
                <h1><?php $formArray['prenom'] ?></h1><br>
                <h1>Intitul&eacute; du poste</h1>
            </section>
            <section id = "left">
                <h2>Informations</h2>
                    <h3>Contact</h3>
                        <p>Email</p>
                            
                        <p>T&eacute;l&eacute;phone</p>
                        <p>Linkedin</p>
                        <p>GitHub</p>
                    <h3>Biographie</h3>
                        <p></p>
                    <h3>Loisirs</h3>
                        <ol>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ol>
            </section>
            <section id = "right">
                <h2>COMP&#201;TENCES</h2>
                    <h3>Langages des programmation</h3>
                        <ol>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ol>
                    <h3>Frameworks & Librairies</h3>
                        <ol>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ol>
                    <h3>Logiciels</h3>
                        <ol>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ol>
                    <h3>Langues</h3>
                        <ol>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ol>
            </section>
        </section>
    </body>
</html>