<?php
require 'index.php';
?>

<!DOCTYPE html>
<html>
    <head>
        <title>CV</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link href="cv.css" rel="stylesheet">
    </head>
    <body>
        <section id ="wholepage">
            <section id = "top">
                <h1><?php echo $formArray['prenom']; ?> <?php echo $formArray['nom']; ?></h1><br>
                <h1>Intitul&eacute; du poste</h1>
            </section>
            <section id = "left">
                <h2>Informations</h2>
                    <h3>Contact</h3>
                        <p>Email: <?php echo $formArray['email']; ?></p>
                        <p>T&eacute;l&eacute;phone: <?php echo $formArray['phone']; ?></p>
                        <p>Linkedin: <?php echo $formArray['linkedin']; ?></p>
                    <h3>Biographie</h3>
                        <p><?php echo $formArray['biographie']; ?></p>
                    <h3>Loisirs</h3>
                        <ol>
                            <li><?php echo $formArray['loisir1']; ?></li>
                            <li><?php echo $formArray['loisir2']; ?></li>
                            <li><?php echo $formArray['loisir3']; ?></li>
                            <li><?php echo $formArray['loisir4']; ?></li>
                        </ol>
            </section>
            <section id = "right">
                <h2>COMP&#201;TENCES</h2>
                    <h3>Langages des programmation</h3>
                        <ol>
                            <?php foreach($formArray['prog'] as $progs){ ?>
                            <li><?php echo $progs; ?></li>
                            <?php }; ?>
                        </ol>
                    <h3>Frameworks & Librairies</h3>
                        <ol>
                            <?php foreach($formArray['frameworks'] as $framework){ ?>
                            <li><?php echo $framework; ?></li>
                            <?php }; ?>
                        </ol>
                    <h3>Logiciels</h3>
                        <ol>
                            <?php foreach($formArray['softwares'] as $software){ ?>
                            <li><?php echo $software; ?></li>
                            <?php }; ?>
                        </ol>
                    <h3>Langues</h3>
                        <ol>
                            <?php foreach($formArray['langs'] as $lang){ ?>
                            <li><?php echo $lang; ?></li>
                            <?php }; ?>
                        </ol>
            </section>
        </section>
    </body>
</html>