<!DOCTYPE html>
<html lang="fr">
    <head>
        
    </head>
    <body>
        <main>
            <form>
                <fieldset>
                    <label for="color">Choisir page</label><br>
                    <select name="pages" id="pages">
                        <option value="">Choisir page</option>
                        <option value="about">About</option>
                        <option value="contact">Contact</option>
                    </select>
                </fieldset>
            </form>
        </main>
    </body>
</html>