<h2>Frameworks & Librairies</h2>
<fieldset>
    <input type="checkbox" id="sass" name="sass[]">
    <label for="sass">Sass</label><br>
    <input type="checkbox" id="bootstrap" name="bootstrap[]">
    <label for="bootstrap">Bootstrap</label><br>
    <input type="checkbox" id="symphony" name="symphony[]">
    <label for="symphony">Symphony</label><br>
    <input type="checkbox" id="laravel" name="laravel[]">
    <label for="laravel">Laravel</label><br>
</fieldset>