<h2>Frameworks & Librairies</h2>
<fieldset>
    <input type="checkbox" id="sass" name="frameworks[]" value="sass">
    <label for="sass">Sass</label><br>
    <input type="checkbox" id="bootstrap" name="frameworks[]" value="bootstrap">
    <label for="bootstrap">Bootstrap</label><br>
    <input type="checkbox" id="symphony" name="frameworks[]" value="symphony">
    <label for="symphony">Symphony</label><br>
    <input type="checkbox" id="laravel" name="frameworks[]" value="laravel">
    <label for="laravel">Laravel</label><br>
</fieldset>