<h1>INFORMATIONS</h1>
<fieldset>
    <label><b>Nom</b></label><br>
    <input type="text" name="nom" required><br>
    <label><b>Pr&eacute;nom</b></label><br>
    <input type="text" name="prenom" required><br>
    <label><b>Email</b></label><br>           
    <input type="text" name="email" required><br>
    <label><b>T&eacute;l&eacute;phone</b></label><br>
    <input type="text" name="phone" required><br>
    <label><b>Linkedin</b></label><br>
    <input type="text" name="linkedin" required><br>
    <label><b>Biographie</b></label><br>
    <input type="text" name="biographie" required><br>
    <label><b>Loisir 1</b></label><br>
    <input type="text" name="loisir1" required><br>
    <label><b>Loisir 2</b></label><br>
    <input type="text" name="loisir2" required><br>
    <label><b>Loisir 3</b></label><br>
    <input type="text" name="loisir3" required><br>
    <label><b>Loisir 4</b></label><br>
    <input type="text" name="loisir4" required><br>
</fieldset>