<h2>Langues</h2>
<fieldset>
    <input type="checkbox" id="francais" name="francais[]">
    <label for="français">Français</label><br>
    <input type="checkbox" id="anglais" name="anglais[]">
    <label for="anglais">Anglais</label><br>
    <input type="checkbox" id="arabe" name="arabe[]">
    <label for="arabe">Arabe</label><br>
    <input type="checkbox" id="breton" name="breton[]">
    <label for="breton">Breton</label><br>
    <input type="checkbox" id="espagnol" name="espagnol[]">
    <label for="espagnol">Espagnol</label>
</fieldset>