<h2>Langues</h2>
<fieldset>
    <input type="checkbox" id="francais" name="langs[]" value="francais">
    <label for="français">Français</label><br>
    <input type="checkbox" id="anglais" name="langs[]" value="anglais">
    <label for="anglais">Anglais</label><br>
    <input type="checkbox" id="arabe" name="langs[]" value="arabe">
    <label for="arabe">Arabe</label><br>
    <input type="checkbox" id="breton" name="langs[]" value="breton">
    <label for="breton">Breton</label><br>
    <input type="checkbox" id="espagnol" name="langs[]" value="espagnol">
    <label for="espagnol">Espagnol</label>
</fieldset>