<h1>COMP&#201;TENCES</h1>
<h2>Langages de Programmation</h2>
<fieldset>
    <input type="checkbox" id="html" name="html">
    <label for="html">HTML</label><br>
    <input type="checkbox" id="css" name="css">
    <label for="css">CSS</label><br>
    <input type="checkbox" id="arabe" name="arabe">
    <label for="arabe">JavaScript</label><br>
    <input type="checkbox" id="php" name="php">
    <label for="php">PHP</label><br>
    <input type="checkbox" id="sql" name="sql">
    <label for="sql">SQL</label>
</fieldset>