<h1>COMP&#201;TENCES</h1>
<h2>Langages de Programmation</h2>
<fieldset>
    <input type="checkbox" id="html" name="prog[]" value="html">
    <label for="html">HTML</label><br>
    <input type="checkbox" id="css" name="prog[]" value="css">
    <label for="css">CSS</label><br>
    <input type="checkbox" id="js" name="prog[]" value="js">
    <label for="js">JavaScript</label><br>
    <input type="checkbox" id="php" name="prog[]" value="php">
    <label for="php">PHP</label><br>
    <input type="checkbox" id="sql" name="prog[]" value="sql">
    <label for="sql">SQL</label>
</fieldset>