<h2>Logiciels</h2>
<fieldset>
    <input type="checkbox" id="photoshop" name="softwares[]" value="photoshop">
    <label for="photoshop">Photoshop</label><br>
    <input type="checkbox" id="illusrator" name="softwares[]" value="illusrator">
    <label for="illusrator">Illusrator</label><br>
    <input type="checkbox" id="xd" name="softwares[]" value="xd">
    <label for="xd">XD</label><br>
    <input type="checkbox" id="figma" name="softwares[]" value="figma">
    <label for="figma">Figma</label><br>
</fieldset>