<h2>Logiciels</h2>
<fieldset>
    <input type="checkbox" id="photoshop" name="photoshop[]">
    <label for="photoshop">Photoshop</label><br>
    <input type="checkbox" id="illusrator" name="illusrator[]">
    <label for="illusrator">Illusrator</label><br>
    <input type="checkbox" id="xd" name="xd[]">
    <label for="xd">XD</label><br>
    <input type="checkbox" id="figma" name="figma[]">
    <label for="figma">Figma</label><br>
</fieldset>